import {
  Activity,
  Archive,
  ArrowRight,
  AtSign,
  Award,
  BadgeHelp,
  Ban,
  BarChart3,
  Binary,
  Blocks,
  Book,
  BookMarked,
  BookOpen,
  Bookmark,
  Box,
  Boxes,
  Braces,
  Bug,
  Cable,
  CheckCircle2,
  ChevronRight,
  Circle,
  Clipboard,
  ClipboardList,
  Cloud,
  CloudCog,
  CloudLightning,
  Code,
  Code2,
  Cog,
  Compass,
  Container,
  Cpu,
  Crown,
  Database,
  DatabaseZap,
  Diamond,
  Download,
  Eye,
  EyeOff,
  File,
  FileCode,
  FileCode2,
  FileJson,
  FileText,
  Files,
  Fingerprint,
  Flag,
  Flame,
  Folder,
  FolderOpen,
  Gamepad2,
  Gauge,
  Gem,
  GitBranch,
  GitCommit,
  GitFork,
  GitMerge,
  GitPullRequest,
  Globe,
  GraduationCap,
  HardDrive,
  Hash,
  Heart,
  HelpCircle,
  Hexagon,
  Inbox,
  Info,
  KeyRound,
  Keyboard,
  Laptop,
  Layers,
  LayoutGrid,
  Library,
  Lightbulb,
  LineChart,
  Link2,
  ListChecks,
  Lock,
  Mail,
  Map,
  MapPin,
  Medal,
  MemoryStick,
  MessageCircle,
  MessageSquare,
  Mic,
  Milestone,
  Monitor,
  Mouse,
  MoveRight,
  Network,
  Newspaper,
  Notebook,
  NotebookPen,
  Package,
  PackageOpen,
  PenTool,
  PieChart,
  Plug,
  Puzzle,
  Radio,
  RefreshCw,
  Repeat,
  Rocket,
  RotateCw,
  Route,
  Router,
  Rss,
  ScanFace,
  School,
  ScrollText,
  Send,
  Server,
  ServerCog,
  Settings,
  Settings2,
  Share2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShieldOff,
  Shuffle,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  Square,
  Star,
  StickyNote,
  Table,
  Tablet,
  Target,
  Telescope,
  Terminal,
  ThumbsUp,
  Trash2,
  TrendingDown,
  TrendingUp,
  Triangle,
  Trophy,
  Unlock,
  Upload,
  UserCheck,
  UserPlus,
  UserX,
  Users,
  Video,
  Wand2,
  Webhook,
  Wifi,
  Workflow,
  Wrench,
  XCircle,
  Zap,
  type LucideIcon,
} from "lucide-react";

// Danh sach icon curated cho module Series (icon truoc entry sidebar/stats
// bar/lien ket ngoai) - dung chung 1 pattern voi GroupIconPicker.tsx
// (home-journey/group-icons.tsx), nhung MO RONG NHIEU HON (yeu cau nguoi
// dung: "ít icon quá. Tôi cần nhiều hơn, thật nhiều vào. Lấy lucide về cũng
// được") - phu rong sang ca cac chu de tech/cloud/infra/security/docs/data,
// khong con gioi han hep o "thong ke/lien ket ngoai" nhu truoc, vi noi dung
// Series thuc te da da dang hon (vd "AWS Solutions Architect").
export const SERIES_ICON_OPTIONS: { name: string; icon: LucideIcon }[] = [
  // Tech / cloud / infra
  { name: "Cloud", icon: Cloud },
  { name: "CloudCog", icon: CloudCog },
  { name: "CloudLightning", icon: CloudLightning },
  { name: "Server", icon: Server },
  { name: "ServerCog", icon: ServerCog },
  { name: "Database", icon: Database },
  { name: "DatabaseZap", icon: DatabaseZap },
  { name: "HardDrive", icon: HardDrive },
  { name: "MemoryStick", icon: MemoryStick },
  { name: "Cpu", icon: Cpu },
  { name: "Network", icon: Network },
  { name: "Router", icon: Router },
  { name: "Wifi", icon: Wifi },
  { name: "Globe", icon: Globe },
  { name: "Container", icon: Container },
  { name: "Boxes", icon: Boxes },
  { name: "Box", icon: Box },
  { name: "Package", icon: Package },
  { name: "PackageOpen", icon: PackageOpen },
  { name: "Layers", icon: Layers },
  { name: "Blocks", icon: Blocks },
  { name: "Puzzle", icon: Puzzle },
  { name: "Workflow", icon: Workflow },
  { name: "Webhook", icon: Webhook },
  { name: "Cable", icon: Cable },
  { name: "Plug", icon: Plug },
  { name: "Cog", icon: Cog },
  { name: "Settings", icon: Settings },
  { name: "Settings2", icon: Settings2 },
  { name: "SlidersHorizontal", icon: SlidersHorizontal },
  { name: "Wrench", icon: Wrench },

  // Dev / code
  { name: "Code", icon: Code },
  { name: "Code2", icon: Code2 },
  { name: "Terminal", icon: Terminal },
  { name: "Braces", icon: Braces },
  { name: "Binary", icon: Binary },
  { name: "Bug", icon: Bug },
  { name: "GitBranch", icon: GitBranch },
  { name: "GitCommit", icon: GitCommit },
  { name: "GitFork", icon: GitFork },
  { name: "GitMerge", icon: GitMerge },
  { name: "GitPullRequest", icon: GitPullRequest },

  // Security
  { name: "Shield", icon: Shield },
  { name: "ShieldCheck", icon: ShieldCheck },
  { name: "ShieldAlert", icon: ShieldAlert },
  { name: "ShieldOff", icon: ShieldOff },
  { name: "Lock", icon: Lock },
  { name: "Unlock", icon: Unlock },
  { name: "KeyRound", icon: KeyRound },
  { name: "Fingerprint", icon: Fingerprint },
  { name: "ScanFace", icon: ScanFace },
  { name: "Eye", icon: Eye },
  { name: "EyeOff", icon: EyeOff },
  { name: "UserCheck", icon: UserCheck },
  { name: "UserX", icon: UserX },
  { name: "Ban", icon: Ban },

  // Docs / reference
  { name: "BookOpen", icon: BookOpen },
  { name: "Book", icon: Book },
  { name: "BookMarked", icon: BookMarked },
  { name: "Bookmark", icon: Bookmark },
  { name: "Library", icon: Library },
  { name: "Notebook", icon: Notebook },
  { name: "NotebookPen", icon: NotebookPen },
  { name: "FileText", icon: FileText },
  { name: "File", icon: File },
  { name: "Files", icon: Files },
  { name: "FileCode", icon: FileCode },
  { name: "FileCode2", icon: FileCode2 },
  { name: "FileJson", icon: FileJson },
  { name: "ClipboardList", icon: ClipboardList },
  { name: "Clipboard", icon: Clipboard },
  { name: "ScrollText", icon: ScrollText },
  { name: "Newspaper", icon: Newspaper },
  { name: "StickyNote", icon: StickyNote },
  { name: "Archive", icon: Archive },
  { name: "Folder", icon: Folder },
  { name: "FolderOpen", icon: FolderOpen },
  { name: "Inbox", icon: Inbox },

  // Hoc tap / dinh huong
  { name: "GraduationCap", icon: GraduationCap },
  { name: "School", icon: School },
  { name: "Lightbulb", icon: Lightbulb },
  { name: "Compass", icon: Compass },
  { name: "Map", icon: Map },
  { name: "MapPin", icon: MapPin },
  { name: "Route", icon: Route },
  { name: "Milestone", icon: Milestone },
  { name: "Flag", icon: Flag },
  { name: "Target", icon: Target },
  { name: "Telescope", icon: Telescope },

  // Danh hieu / trang thai
  { name: "Star", icon: Star },
  { name: "Award", icon: Award },
  { name: "Trophy", icon: Trophy },
  { name: "Medal", icon: Medal },
  { name: "Crown", icon: Crown },
  { name: "Gem", icon: Gem },
  { name: "Sparkles", icon: Sparkles },
  { name: "Zap", icon: Zap },
  { name: "Flame", icon: Flame },
  { name: "Rocket", icon: Rocket },
  { name: "Heart", icon: Heart },
  { name: "ThumbsUp", icon: ThumbsUp },
  { name: "CheckCircle2", icon: CheckCircle2 },
  { name: "XCircle", icon: XCircle },
  { name: "HelpCircle", icon: HelpCircle },
  { name: "Info", icon: Info },
  { name: "Wand2", icon: Wand2 },

  // Giao tiep / mang xa hoi
  { name: "MessageCircle", icon: MessageCircle },
  { name: "MessageSquare", icon: MessageSquare },
  { name: "Mail", icon: Mail },
  { name: "Send", icon: Send },
  { name: "AtSign", icon: AtSign },
  { name: "Video", icon: Video },
  { name: "Mic", icon: Mic },
  { name: "Radio", icon: Radio },
  { name: "Rss", icon: Rss },
  { name: "Share2", icon: Share2 },
  { name: "Users", icon: Users },
  { name: "UserPlus", icon: UserPlus },

  // Du lieu / thong ke
  { name: "BarChart3", icon: BarChart3 },
  { name: "LineChart", icon: LineChart },
  { name: "PieChart", icon: PieChart },
  { name: "TrendingUp", icon: TrendingUp },
  { name: "TrendingDown", icon: TrendingDown },
  { name: "Activity", icon: Activity },
  { name: "Gauge", icon: Gauge },
  { name: "Table", icon: Table },
  { name: "ListChecks", icon: ListChecks },
  { name: "Hash", icon: Hash },

  // Lien ket / tep
  { name: "Link2", icon: Link2 },
  { name: "Download", icon: Download },
  { name: "Upload", icon: Upload },
  { name: "Trash2", icon: Trash2 },

  // Thiet bi
  { name: "Laptop", icon: Laptop },
  { name: "Monitor", icon: Monitor },
  { name: "Smartphone", icon: Smartphone },
  { name: "Tablet", icon: Tablet },
  { name: "Keyboard", icon: Keyboard },
  { name: "Mouse", icon: Mouse },
  { name: "Gamepad2", icon: Gamepad2 },

  // Dieu huong / chuyen dong
  { name: "ArrowRight", icon: ArrowRight },
  { name: "MoveRight", icon: MoveRight },
  { name: "ChevronRight", icon: ChevronRight },
  { name: "RefreshCw", icon: RefreshCw },
  { name: "RotateCw", icon: RotateCw },
  { name: "Repeat", icon: Repeat },
  { name: "Shuffle", icon: Shuffle },

  // Hinh khoi co ban / bo cuc
  { name: "Circle", icon: Circle },
  { name: "Square", icon: Square },
  { name: "Triangle", icon: Triangle },
  { name: "Hexagon", icon: Hexagon },
  { name: "Diamond", icon: Diamond },
  { name: "LayoutGrid", icon: LayoutGrid },
  { name: "PenTool", icon: PenTool },
];

const SERIES_ICON_MAP: Record<string, LucideIcon> = Object.fromEntries(
  SERIES_ICON_OPTIONS.map((o) => [o.name, o.icon]),
);

// Render icon Series theo TEN da luu - fallback ve BadgeHelp khi chua chon/
// ten khong con hop le, dung chung o SeriesStatsBar.tsx (trang cong khai) va
// preview trong SeriesForm.tsx (phai khop 100% - cung 1 ham resolve).
export function SeriesIconGlyph({
  name,
  size = 15,
  strokeWidth = 1.9,
  className,
}: {
  name?: string | null;
  size?: number;
  strokeWidth?: number;
  className?: string;
}) {
  const Icon = (name && SERIES_ICON_MAP[name]) || BadgeHelp;
  return <Icon size={size} strokeWidth={strokeWidth} className={className} />;
}
