import {
  Atom,
  BarChart3,
  BookOpen,
  Bot,
  Briefcase,
  Brain,
  Brush,
  Bug,
  Camera,
  Cloud,
  Code2,
  Coffee,
  Compass,
  Cpu,
  Database,
  Dna,
  Dumbbell,
  Film,
  FlaskConical,
  Folder,
  Gamepad2,
  GitBranch,
  Globe,
  GraduationCap,
  Handshake,
  Heart,
  Languages,
  Leaf,
  Library,
  Lightbulb,
  Map,
  Mic,
  Microscope,
  Mountain,
  Music,
  Network,
  NotebookPen,
  Orbit,
  Palette,
  PenTool,
  Plane,
  Puzzle,
  Rocket,
  Server,
  Shield,
  Sparkles,
  Star,
  Sun,
  Target,
  Telescope,
  Terminal,
  TrendingUp,
  Trophy,
  Utensils,
  Wallet,
  type LucideIcon,
} from "lucide-react";

// Danh sach icon curated (lucide-react - thu vien icon dang dung xuyen suot
// app, ~6000 icon nen du da dang, khong can them thu vien moi) cho
// GroupIconPicker.tsx. Luu TEN EXPORT (vd "BookOpen") vao KnowledgeGroup.icon,
// KHONG luu raw glyph - khac Workspace.icon (chua tung dung toi o UI).
export const GROUP_ICON_OPTIONS: { name: string; icon: LucideIcon }[] = [
  { name: "BookOpen", icon: BookOpen },
  { name: "GraduationCap", icon: GraduationCap },
  { name: "Lightbulb", icon: Lightbulb },
  { name: "Brain", icon: Brain },
  { name: "PenTool", icon: PenTool },
  { name: "Library", icon: Library },
  { name: "NotebookPen", icon: NotebookPen },
  { name: "Code2", icon: Code2 },
  { name: "Terminal", icon: Terminal },
  { name: "Cpu", icon: Cpu },
  { name: "Database", icon: Database },
  { name: "Server", icon: Server },
  { name: "Cloud", icon: Cloud },
  { name: "Bug", icon: Bug },
  { name: "GitBranch", icon: GitBranch },
  { name: "Rocket", icon: Rocket },
  { name: "Bot", icon: Bot },
  { name: "Network", icon: Network },
  { name: "FlaskConical", icon: FlaskConical },
  { name: "Atom", icon: Atom },
  { name: "Dna", icon: Dna },
  { name: "Microscope", icon: Microscope },
  { name: "Telescope", icon: Telescope },
  { name: "Orbit", icon: Orbit },
  { name: "Palette", icon: Palette },
  { name: "Camera", icon: Camera },
  { name: "Film", icon: Film },
  { name: "Music", icon: Music },
  { name: "Mic", icon: Mic },
  { name: "Brush", icon: Brush },
  { name: "Briefcase", icon: Briefcase },
  { name: "BarChart3", icon: BarChart3 },
  { name: "TrendingUp", icon: TrendingUp },
  { name: "Wallet", icon: Wallet },
  { name: "Target", icon: Target },
  { name: "Handshake", icon: Handshake },
  { name: "Languages", icon: Languages },
  { name: "Globe", icon: Globe },
  { name: "Dumbbell", icon: Dumbbell },
  { name: "Utensils", icon: Utensils },
  { name: "Plane", icon: Plane },
  { name: "Coffee", icon: Coffee },
  { name: "Heart", icon: Heart },
  { name: "Leaf", icon: Leaf },
  { name: "Sun", icon: Sun },
  { name: "Mountain", icon: Mountain },
  { name: "Compass", icon: Compass },
  { name: "Map", icon: Map },
  { name: "Star", icon: Star },
  { name: "Trophy", icon: Trophy },
  { name: "Shield", icon: Shield },
  { name: "Puzzle", icon: Puzzle },
  { name: "Gamepad2", icon: Gamepad2 },
  { name: "Sparkles", icon: Sparkles },
  { name: "Folder", icon: Folder },
];

const GROUP_ICON_MAP: Record<string, LucideIcon> = Object.fromEntries(
  GROUP_ICON_OPTIONS.map((o) => [o.name, o.icon]),
);

// Component render icon cua 1 nhom kien thuc theo TEN da luu - fallback ve
// Folder khi chua chon/ten khong con hop le (vd danh sach curated doi sau
// nay), dung chung o moi noi can hien icon nhom (card catalog, header
// sidebar...).
export function GroupIconGlyph({
  name,
  size = 15,
  strokeWidth = 1.9,
  className,
}: {
  name?: string | null;
  size?: number;
  strokeWidth?: number;
  className?: string;
}) {
  const Icon = (name && GROUP_ICON_MAP[name]) || Folder;
  return <Icon size={size} strokeWidth={strokeWidth} className={className} />;
}
